spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.168.10
    port: 5672
    username: sulwan
    password: 123456a
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost